### ISSUE TITLE
[<Samipsolutions>] MountVolume.SetUp failed for volume "gateway-configmap" : configmap "pod-gateway" not found

### ISSUE THREAD

**Issue by faisalbasha19** [samipsolutions/helm-charts#40]
### Helm chart name

pod-gateway

### Helm chart version

pod-gateway-5.6.2

### Container name

ghcr.io/k8s-at-home/pod-gateway

### Container tag

v1.6.1

### Description

This issue happens when I create a test deployment in the vpn namespace, my vpn namespace has the required label
routed-gateway=true. When describe this test pod I get the following error:

MountVolume.SetUp failed for volume "gateway-configmap" : configmap "pod-gateway" not found
Unable to attach or mount volumes: unmounted volumes=[gateway-configmap], unattached volumes=[gateway-configmap kube-api-access-4c4qq]: timed out waiting for the condition

I can see the configmap:  pod-gateway in default namespace

kubectl describe cm pod-gateway
```
Name:         pod-gateway
Namespace:    default
Labels:       app.kubernetes.io/instance=pod-gateway
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=pod-gateway
              app.kubernetes.io/version=v1.6.1
              helm.sh/chart=pod-gateway-5.6.2
Annotations:  meta.helm.sh/release-name: pod-gateway
              meta.helm.sh/release-namespace: default

Data
====
nat.conf:
----
# Generated by pod-gateway

settings.sh:
----
#!/bin/sh
# Generated by pod-gateway
DNS_LOCAL_CIDRS="local"
NOT_ROUTED_TO_GATEWAY_CIDRS=""
VPN_BLOCK_OTHER_TRAFFIC="false"
VPN_INTERFACE="tun0"
VPN_LOCAL_CIDRS="10.0.0.0/8 192.168.0.0/16"
VPN_TRAFFIC_PORT="1194"
VXLAN_GATEWAY_FIRST_DYNAMIC_IP="20"
VXLAN_ID="42"
VXLAN_IP_NETWORK="172.16.0"


BinaryData
====
```

what could be the issue for this?

### Expected result

the test pod should be in running state.

### Helm values to reproduce

```YAML
just the default values
```

**Comment by samip5** [comment]
I don't maintain that chart anymore, will not be fixed. The continuum of it is here: https://github.com/angelnu/helm-charts/tree/main/charts/apps/pod-gateway
